import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@shared/styles/globals.scss";
import { ReactNode } from "react";
import { routing } from "@core/locale/i18n/routing";
import { getMessages } from "next-intl/server";
import { hasLocale, Locale } from "next-intl";
import { notFound } from "next/navigation";
import IntlProvider from "@core/context/intl-provider";
import { cn } from "@shared/lib/utils";
import PageProgress from "@components/atoms/page-progress";
import { headers } from "next/headers";
import { selfURL } from "@shared/env";
import { openGraphConstructor } from "@shared/lib/og-constructor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateMetadata(): Promise<Metadata> {
  const headersStore = await headers();
  const pathname = headersStore.get("x-pathname");

  const og = await openGraphConstructor({
    title: "Create Next App",
    description: "Generated by create next app",
  });

  return {
    ...og,
    metadataBase: selfURL ? new URL(selfURL) : null,
    alternates: { canonical: pathname },
  };
}

// export const revalidate = 120;

// export function generateStaticParams() {
//   return routing.locales.map((locale) => ({ locale }));
// }

interface RootLayoutProps {
  children: ReactNode;
  params: Promise<{ locale: Locale }>;
}

async function RootLayout({ children, params }: Readonly<RootLayoutProps>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) notFound();

  const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <body
        suppressHydrationWarning
        className={cn(geistSans.variable, geistMono.variable, "antialiased")}
      >
        <IntlProvider
          locale={locale}
          messages={messages}
        >
          <PageProgress />
          {children}
        </IntlProvider>
      </body>
    </html>
  );
}

export default RootLayout;
